########## Spring Properties ##########
server:
  servlet:
    context-path: /irm_server
  port: 5444
spring:
  application:
    name: irm_server
  datasource:    
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

########## Application Properties ##########
irm:
  client-id: irm-client
  client-secret: irm-secret
